language: php

php:
  - 7.0

script: 
  - echo $KEY > ./travis-ci
  - git config core.sshCommand "ssh -i ./travis-ci -F /dev/null"
  - git config user.email "travis@travis-ci.org"
  - git config user.name "Travis CI"
  - git remote add origin git@github.com:deployphp/distribution.git
  - git branch --set-upstream-to origin/master
  - php update
